2024-09-26 12:07:06 - INFO   - [automate_parameter_category(): 31] - Initiated parameter automation
2024-09-26 12:07:09 - INFO   - [automate_parameter_category(): 68] - Parameter Category Information Exists
2024-09-26 12:07:09 - INFO   - [automate_parameter_groups(): 31] - Initiated parameter automation
2024-09-26 12:22:41 - ERROR  - [<module>(): 15] - FileNotFoundError: File not found: D:\Automation_20092024\Automation\template1.xlxs
Traceback (most recent call last):
  File "D:\Automation_20092024\Automation\app.py", line 12, in <module>
    raise FileNotFoundError(f"File not found: {file_path}")
FileNotFoundError: File not found: D:\Automation_20092024\Automation\template1.xlxs
2024-09-26 12:23:29 - ERROR  - [<module>(): 15] - FileNotFoundError: File not found: D:\Automation_20092024\Automation\parameter_template\template1.xlxs
Traceback (most recent call last):
  File "D:\Automation_20092024\Automation\app.py", line 12, in <module>
    raise FileNotFoundError(f"File not found: {file_path}")
FileNotFoundError: File not found: D:\Automation_20092024\Automation\parameter_template\template1.xlxs
2024-09-26 12:24:31 - INFO   - [automate_parameter_category(): 31] - Initiated parameter automation
2024-09-26 12:24:34 - INFO   - [automate_parameter_category(): 68] - Parameter Category Information Exists
2024-09-26 12:24:34 - INFO   - [automate_parameter_groups(): 31] - Initiated parameter automation
2024-09-26 12:24:37 - INFO   - [automate_parameter_groups(): 67] - Parameter Groups Information Exists

2024-09-26 12:24:37 - INFO   - [automate_parameter_creation(): 31] - Initiated parameter automation
2024-09-26 12:24:46 - INFO   - [automate_parameter_category(): 31] - Initiated parameter automation
2024-09-26 12:24:49 - INFO   - [automate_parameter_category(): 68] - Parameter Category Information Exists
2024-09-26 12:24:49 - INFO   - [automate_parameter_groups(): 31] - Initiated parameter automation
2024-09-26 12:24:52 - INFO   - [automate_parameter_groups(): 67] - Parameter Groups Information Exists

2024-09-26 12:24:52 - INFO   - [automate_parameter_creation(): 31] - Initiated parameter automation
2024-09-26 12:24:55 - ERROR  - [automate_parameter_creation(): 52] - Error while automating parameter: 'ParameterCreationHandler' object has no attribute 'get_data_type'
Traceback (most recent call last):
  File "D:\Automation_20092024\Automation\scripts\core\handlers\parameter_creation.py", line 41, in automate_parameter_creation
    get_data_type = self.get_data_type()
                    ^^^^^^^^^^^^^^^^^^
AttributeError: 'ParameterCreationHandler' object has no attribute 'get_data_type'
2024-09-26 12:26:18 - INFO   - [automate_parameter_category(): 31] - Initiated parameter automation
2024-09-26 12:26:21 - INFO   - [automate_parameter_category(): 68] - Parameter Category Information Exists
2024-09-26 12:26:21 - INFO   - [automate_parameter_groups(): 31] - Initiated parameter automation
2024-09-26 12:26:25 - INFO   - [automate_parameter_groups(): 67] - Parameter Groups Information Exists

2024-09-26 12:26:25 - INFO   - [automate_parameter_creation(): 31] - Initiated parameter automation
2024-09-26 12:26:27 - ERROR  - [automate_parameter_creation(): 52] - Error while automating parameter: 'ParameterCreationHandler' object has no attribute 'get_data_type'
Traceback (most recent call last):
  File "D:\Automation_20092024\Automation\scripts\core\handlers\parameter_creation.py", line 41, in automate_parameter_creation
    get_data_type = self.get_data_type()
                    ^^^^^^^^^^^^^^^^^^
AttributeError: 'ParameterCreationHandler' object has no attribute 'get_data_type'
